### PR TITLE
Document the format for data updates

### PR DESCRIPTION
**Pull request by ekimekim**
This PR fills out the section on data update messages, including how to parse the content into a sequence of data values.

### CODE REVIEW

**Comment by rgbkrk** [comment]
:+1:

**Comment by luckydonald** [comment]
Included this in [luckydonald/JavaPipBoyServe/PROTOCOL.md](https://github.com/luckydonald/JavaPipBoyServer/blob/master/PROTOCOL.md) ([permalink](https://github.com/luckydonald/JavaPipBoyServer/blob/b039b6c76380b077451e3c70f43c89abca7e5a84/PROTOCOL.md)).

**Comment by luckydonald** [comment]
You have write permissions here too?

**Comment by rgbkrk** [comment]
Apparently! I just noticed after your comment. Nice to see you again.

**Comment by luckydonald** [comment]
Yay! In fact I am still working on my [Pipboy server implementation](https://github.com/luckydonald/JavaPipBoyServer/) now and then,
and now also on a quick-to-use [byte parser](https://github.com/luckydonald/JavaPipBoyServer/blob/master/parser.html) ([permalink](https://github.com/luckydonald/JavaPipBoyServer/blob/bb01c48c8d34b4fcc4dd6b8f5ff36668d72cffbd/parser.html))
[image](https://github.com/luckydonald/JavaPipBoyServer/blob/bb01c48c8d34b4fcc4dd6b8f5ff36668d72cffbd/parser.html)

**Pull request merged**
